/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    fontFamily: {
      sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
    },
    extend: {
      colors: {
        'on-tertiary-fixed': '#311300',
        'on-tertiary': '#512400',
        'surface-container-highest': '#36333e',
        'surface-container': '#211e28',
        'secondary-container': '#00e3fd',
        'on-tertiary-fixed-variant': '#733600',
        'secondary-fixed': '#9cf0ff',
        'on-primary-fixed': '#20005f',
        'tertiary-fixed': '#ffdbc7',
        'surface-variant': '#36333e',
        'inverse-on-surface': '#322f3a',
        'surface-container-lowest': '#0f0d16',
        'surface-bright': '#3b3743',
        'on-tertiary-container': '#fff7f4',
        'surface-container-high': '#2b2833',
        'on-primary': '#370096',
        'outline-variant': '#494455',
        'on-background': '#e6e0ee',
        'inverse-surface': '#e6e0ee',
        'inverse-primary': '#6833ea',
        'surface-dim': '#14121c',
        'on-error': '#690005',
        'primary-fixed-dim': '#cdbdff',
        'on-secondary-fixed': '#001f24',
        'on-secondary-container': '#00616d',
        'on-primary-container': '#fcf6ff',
        'tertiary-container': '#b55800',
        'surface-tint': '#cdbdff',
        'on-primary-fixed-variant': '#4f00d0',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#004f58',
        'primary-fixed': '#e8deff',
        'on-secondary': '#00363d',
        'on-surface': '#e6e0ee',
        'tertiary-fixed-dim': '#ffb688',
        'surface-container-low': '#1d1a24',
        'tertiary': '#ffb688',
        'on-surface-variant': '#cac3d8',
        'error-container': '#93000a',
        'primary-container': '#7c4dff',
        'secondary-fixed-dim': '#00daf3',
        background: 'rgb(var(--background) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'text-primary': 'rgb(var(--primary) / <alpha-value>)',
        'text-body': 'rgb(var(--text-body) / <alpha-value>)',
        'text-muted': 'rgb(var(--text-muted) / <alpha-value>)',
        border: 'rgb(var(--border-rgb, 228 228 231) / <alpha-value>)',
        success: 'rgb(var(--success-rgb) / <alpha-value>)',
        error: 'rgb(var(--error-rgb) / <alpha-value>)',
        warning: 'rgb(var(--warning-rgb) / <alpha-value>)',
        info: 'rgb(var(--info-rgb) / <alpha-value>)',
      },
      fontFamily: {
        'space-grotesk': ['Space Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '32': '128px',
      },
      borderRadius: {
        none: '0',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        full: '9999px',
      },
      boxShadow: {
        'sm': '0 1px 2px var(--shadow-color, rgba(0,0,0,0.06))',
        'md': '0 4px 12px var(--shadow-color, rgba(0,0,0,0.08))',
        'lg': '0 8px 24px var(--shadow-color, rgba(0,0,0,0.12))',
        'xl': '0 16px 48px var(--shadow-color, rgba(0,0,0,0.16))',
        'glow': '0 0 20px var(--shadow-brand, rgba(99,102,241,0.25))',
        'glow-sm': '0 0 10px var(--shadow-brand, rgba(99,102,241,0.15))',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        'fast': '120ms',
        'normal': '200ms',
        'slow': '350ms',
      },
      animation: {
        'shimmer': 'shimmer 1.5s infinite',
        'float': 'float 6s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.4s ease-out both',
        'slide-in-right': 'slide-in-right 0.3s ease-out both',
        'scale-in': 'scale-in 0.2s ease-out both',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'toast-progress': 'toast-progress linear forwards',
      },
      keyframes: {
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(16px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 8px var(--shadow-brand)' },
          '50%': { boxShadow: '0 0 20px var(--shadow-brand)' },
        },
        'toast-progress': {
          from: { width: '100%' },
          to: { width: '0%' },
        },
      },
      backgroundImage: {
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E\")",
      },
    },
  },
  plugins: [],
}
